name: cerealis_app
description: Mobile App for Cerealis Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  arcore_flutter_plugin:
    path: arcore
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icon/logo_appli.jpg
    - assets/snake.png
    - assets/monkey.png
    - assets/myimages.imgdb
  uses-material-design: true

# Notez que flutter_icons est maintenant Ã  la racine du fichier, en dehors de la section flutter.
flutter_icons:
  image_path: "assets/icon/logo_appli.jpg"
  android: true
